name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Ou la branche que vous souhaitez suivre
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
          npm install @testing-library/jest-dom --save-dev
          npm install @babel/plugin-proposal-private-property-in-object --save-dev
      - name: Run tests
        run: npm test

  # Job de déploiement
  deploy:
    runs-on: ubuntu-latest

    needs: build-and-test   # Ce job dépend du job build-and-test

    steps:
    # 1. Vérifier le code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. (Optionnel) Déployer votre application
    # Exemple de déploiement sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}   # Clé SSH privée pour déploiement
        branch: gh-pages    # Branche de déploiement
        folder: dist        # Dossier à déployer (par exemple 'dist' ou 'build')

